M48
; DRILL file {KiCad 9.0.7} date 2026-02-17T15:39:37+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-17T15:39:37+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X90.0Y-93.42
X90.0Y-130.0
X133.18Y-93.42
X133.18Y-130.0
T2
X90.0Y-40.0
X200.0Y-40.0
X200.0Y-130.0
M30
